### ISSUE TITLE
Integration with Eclipse/STS

### ISSUE THREAD

**Issue by NikhilG100** [oliviercailloux/google-or-tools-java#3]
Hello,

Trying to integrate OR tools with Eclipse/STS running on Windows 10.

I did include below dependency in pom.xml --

<dependency>
    <groupId>io.github.oliviercailloux</groupId>
    <artifactId>google-or-tools</artifactId>
    <version>6.7.2</version>
</dependency>

I set native library path in STS and still after that I see below linker error. 
Please note that I could compile OR tools properly with command prompt.
Can you please help with right pointers as to how can I solve this with Eclipse/STS? 

Caused by: java.lang.UnsatisfiedLinkError: com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init()V
	at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.swig_module_init(Native Method)
	at com.google.ortools.constraintsolver.operations_research_constraint_solverJNI.<clinit>(operations_research_constraint_solverJNI.java:2346)
	at com.google.ortools.constraintsolver.RoutingModel.<clinit>(RoutingModel.java:652)

**Comment by oliviercailloux** [comment]
Hi. I don’t known what Eclipse/STS is. Are you able to use the library in a “normal” project, as exemplified in this very repository?

**Comment by NikhilG100** [comment]
Eclipse is Java Spring Development Suite. (Similar to what Visual Studio
is, but this is for Java Spring).

**Comment by oliviercailloux** [comment]
Closing this, as I don’t understand the problem or what I can do to help.
